package com.magiology.core.init.classload;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.magiology.api.Calculable;
import com.magiology.core.coremod.transformers.ClassTransformerBase;
import com.magiology.forgepowered.packets.core.AbstractPacket;
import com.magiology.util.utilobjects.m_extension.TileEntityM;

import net.minecraft.launchwrapper.IClassTransformer;

public class ClassList{
	
	static final String[]
			classes={
				"com.magiology.api.Calculable",
				"com.magiology.api.connection.Connection",
				"com.magiology.api.connection.ConnectionType",
				"com.magiology.api.connection.IConnection",
				"com.magiology.api.connection.IConnectionFactory",
				"com.magiology.api.connection.IConnectionProvider",
				"com.magiology.api.IObjectFactory",
				"com.magiology.api.lang.bridge.CommandInteractorList",
				"com.magiology.api.lang.bridge.InterfaceWrapper",
				"com.magiology.api.lang.bridge.NetworkProgramHolderWrapper",
				"com.magiology.api.lang.bridge.WorldWrapper",
				"com.magiology.api.lang.ICommandInteract",
				"com.magiology.api.lang.JSProgramContainer",
				"com.magiology.api.lang.program.ProgramCommon",
				"com.magiology.api.lang.program.ProgramDataBase",
				"com.magiology.api.lang.program.ProgramSerializable",
				"com.magiology.api.lang.program.ProgramUsable",
				"com.magiology.api.network.BasicWorldNetworkInterface",
				"com.magiology.api.network.interfaces.registration.DefaultInterface",
				"com.magiology.api.network.interfaces.registration.InterfaceBinder",
				"com.magiology.api.network.interfaces.registration.InterfaceRegistration",
				"com.magiology.api.network.InterfaceTileEntitySaver",
				"com.magiology.api.network.ISidedNetworkComponent",
				"com.magiology.api.network.Messageable",
				"com.magiology.api.network.NetworkBaseComponent",
				"com.magiology.api.network.NetworkInteractBaseComponent",
				"com.magiology.api.network.NetworkInterface",
				"com.magiology.api.network.Redstone",
				"com.magiology.api.network.skeleton.TileEntityNetwork",
				"com.magiology.api.network.skeleton.TileEntityNetworkInteract",
				"com.magiology.api.network.skeleton.TileEntityNetworkPow",
				"com.magiology.api.network.WorldNetworkInterface",
				"com.magiology.api.power.ISidedPower",
				"com.magiology.api.power.PowerCore",
				"com.magiology.api.power.PowerProducer",
				"com.magiology.api.power.PowerUpgrades",
				"com.magiology.api.power.SixSidedBoolean",
				"com.magiology.api.SavableData",
				"com.magiology.api.updateable.Updater",
				"com.magiology.client.gui.container.ArmorContainer",
				"com.magiology.client.gui.container.CommandCenterContainer",
				"com.magiology.client.gui.container.ContainerEmpty",
				"com.magiology.client.gui.container.GuiObjectCustomizeContainer",
				"com.magiology.client.gui.container.ISidedPowerInstructorContainer",
				"com.magiology.client.gui.container.UpgradeContainer",
				"com.magiology.client.gui.custom.DownloadingIcon",
				"com.magiology.client.gui.custom.guiparticels.GuiStandardFX",
				"com.magiology.client.gui.custom.hud.FakeMessageHUD",
				"com.magiology.client.gui.custom.hud.HandModeChangerHUD",
				"com.magiology.client.gui.custom.hud.HUD",
				"com.magiology.client.gui.custom.hud.MainMenuUpdateNotificationHUD",
				"com.magiology.client.gui.custom.hud.SoulFlameHUD",
				"com.magiology.client.gui.custom.hud.StatsDisplayHUD",
				"com.magiology.client.gui.custom.hud.WingModeChangerHUD",
				"com.magiology.client.gui.custom.OnOffGuiButton",
				"com.magiology.client.gui.gui.CraftingGridWOutput",
				"com.magiology.client.gui.gui.GuiArmor",
				"com.magiology.client.gui.gui.GuiCenterContainer",
				"com.magiology.client.gui.gui.GuiContainerAndGuiParticles",
				"com.magiology.client.gui.gui.GuiHologramProjectorMain",
				"com.magiology.client.gui.gui.GuiHoloObjectEditor",
				"com.magiology.client.gui.gui.GuiISidedPowerInstructor",
				"com.magiology.client.gui.gui.GuiJSProgramEditor",
				"com.magiology.client.gui.gui.GuiUpgrade",
				"com.magiology.client.gui.GuiUpdater",
				"com.magiology.client.gui.guiutil.container.ControlBockContainerSlot",
				"com.magiology.client.gui.guiutil.container.CustomSlot",
				"com.magiology.client.gui.guiutil.container.FakeContainer",
				"com.magiology.client.gui.guiutil.container.OnlyShiftClickSlot",
				"com.magiology.client.gui.guiutil.container.UpgItemContainer",
				"com.magiology.client.gui.guiutil.container.UpgItemSlot",
				"com.magiology.client.gui.guiutil.gui.buttons.CleanButton",
				"com.magiology.client.gui.guiutil.gui.buttons.ColoredGuiButton",
				"com.magiology.client.gui.guiutil.gui.buttons.CustomButton",
				"com.magiology.client.gui.guiutil.gui.buttons.InvisivleGuiButton",
				"com.magiology.client.gui.guiutil.gui.buttons.TexturedColoredButton",
				"com.magiology.client.gui.guiutil.gui.ColorSlider",
				"com.magiology.client.gui.guiutil.gui.CraftingGridSlot",
				"com.magiology.client.gui.guiutil.gui.DrawThatSexyDotHelper",
				"com.magiology.client.gui.guiutil.gui.GuiJavaScriptEditor",
				"com.magiology.client.gui.guiutil.gui.GuiSlider",
				"com.magiology.client.gui.guiutil.gui.GuiTextEditor",
				"com.magiology.client.render.aftereffect.AfterRenderRenderer",
				"com.magiology.client.render.aftereffect.LongAfterRenderRenderer",
				"com.magiology.client.render.aftereffect.LongAfterRenderRendererBase",
				"com.magiology.client.render.aftereffect.RenderFirePipeGlow",
				"com.magiology.client.render.aftereffect.RenderFirePipePriorityCube",
				"com.magiology.client.render.aftereffect.RenderNetworkPointerContainerHighlight",
				"com.magiology.client.render.aftereffect.TwoDotsLineRender",
				"com.magiology.client.render.entityrender.BallOfEnergyRenderer",
				"com.magiology.client.render.font.FontRendererMBase",
				"com.magiology.client.render.font.FontRendererMClipped",
				"com.magiology.client.render.itemrender.ItemRendererFirePipe",
				"com.magiology.client.render.itemrender.ItemRendererGenericUpgrade",
				"com.magiology.client.render.itemrender.ItemRendererHelmet42",
				"com.magiology.client.render.itemrender.ItemRendererPants42",
				"com.magiology.client.render.itemrender.ItemRendererPowerCounter",
				"com.magiology.client.render.itemrender.ItemRendererTheHand",
				"com.magiology.client.render.models.entitys.BallOfEnergyModel",
				"com.magiology.client.render.models.ModelWingsFromTheBlackFire",
				"com.magiology.client.render.shaders.BlurRenderer",
				"com.magiology.client.render.shaders.ColorCutRenderer",
				"com.magiology.client.render.shaders.ColorRenderer",
				"com.magiology.client.render.shaders.core.ShaderAspectRenderer",
				"com.magiology.client.render.shaders.core.ShaderRunner",
				"com.magiology.client.render.Textures",
				"com.magiology.client.render.tilerender.isbhrrender.ISBRH",
				"com.magiology.client.render.tilerender.isbhrrender.RenderFireLampISBRH",
				"com.magiology.client.render.tilerender.network.RenderNetworkConductor",
				"com.magiology.client.render.tilerender.network.RenderNetworkController",
				"com.magiology.client.render.tilerender.network.RenderNetworkInterface",
				"com.magiology.client.render.tilerender.network.RenderNetworkRouter",
				"com.magiology.client.render.tilerender.RenderBateryL1",
				"com.magiology.client.render.tilerender.RenderBateryL100",
				"com.magiology.client.render.tilerender.RenderBateryL2",
				"com.magiology.client.render.tilerender.RenderBateryL3",
				"com.magiology.client.render.tilerender.RenderFireLamp",
				"com.magiology.client.render.tilerender.RenderFirePipe",
				"com.magiology.client.render.tilerender.RenderHologramProjector",
				"com.magiology.client.render.tilerender.RenderMultiBox",
				"com.magiology.core.Config",
				"com.magiology.core.coremod.corehooks.ClientHooksM",
				"com.magiology.core.coremod.corehooks.CommonHooksM",
				"com.magiology.core.coremod.corehooks.ServerHooksM",
				"com.magiology.core.coremod.MagiologyCoreMod",
				"com.magiology.core.coremod.TransformerHandler",
				"com.magiology.core.coremod.transformers.ASMBase",
				"com.magiology.core.coremod.transformers.ASMClass",
				"com.magiology.core.coremod.transformers.ASMFuncDesc",
				"com.magiology.core.coremod.transformers.ASMMethod",
				"com.magiology.core.coremod.transformers.classtransf.NativeItemRednerHook",
				"com.magiology.core.coremod.transformers.ClassTransformerBase",
				"com.magiology.core.coremod.transformers.CodeWrapper",
				"com.magiology.core.coremod.transformers.LineWalker",
				"com.magiology.core.coremod.transformers.ValueMaker",
				"com.magiology.core.init.classload.ClassFinder",
				"com.magiology.core.init.classload.ClassList",
				"com.magiology.core.init.MBlocks",
				"com.magiology.core.init.MCreativeTabs",
				"com.magiology.core.init.MEntitys",
				"com.magiology.core.init.MEvents",
				"com.magiology.core.init.MGui",
				"com.magiology.core.init.MInterfaces",
				"com.magiology.core.init.MItems",
				"com.magiology.core.init.MPackets",
				"com.magiology.core.init.MRecepies",
				"com.magiology.core.init.MTileEntitys",
				"com.magiology.core.Magiology",
				"com.magiology.core.MReference",
				"com.magiology.core.MUpdater",
				"com.magiology.forgepowered.events.client.CustomRenderedItem",
				"com.magiology.forgepowered.events.client.HighlightEvent",
				"com.magiology.forgepowered.events.client.MouseEvents",
				"com.magiology.forgepowered.events.client.RenderEvents",
				"com.magiology.forgepowered.events.EntityEvents",
				"com.magiology.forgepowered.events.GameEvents",
				"com.magiology.forgepowered.events.SpecialMovmentEvents",
				"com.magiology.forgepowered.events.TickEvents",
				"com.magiology.forgepowered.packets.core.AbstractPacket",
				"com.magiology.forgepowered.packets.core.AbstractToClientMessage",
				"com.magiology.forgepowered.packets.core.AbstractToServerMessage",
				"com.magiology.forgepowered.packets.packets.toclient.SavableDataWithKeyPacket",
				"com.magiology.forgepowered.packets.packets.toclient.UpdateClientPlayerDataPacket",
				"com.magiology.forgepowered.packets.packets.toserver.ClickHologramPacket",
				"com.magiology.forgepowered.packets.packets.toserver.HandActionPacket",
				"com.magiology.forgepowered.packets.packets.toserver.HologramProjectorUpload",
				"com.magiology.forgepowered.packets.packets.toserver.HoloObjectUploadPacket",
				"com.magiology.forgepowered.packets.packets.toserver.NotifyPointedBoxChangePacket",
				"com.magiology.forgepowered.packets.packets.toserver.OpenGuiPacket",
				"com.magiology.forgepowered.packets.packets.toserver.OpenProgramContainerInGui",
				"com.magiology.forgepowered.packets.packets.toserver.SendWingModePacket",
				"com.magiology.forgepowered.packets.packets.toserver.UploadPlayerDataPacket",
				"com.magiology.forgepowered.proxy.ClientProxy",
				"com.magiology.forgepowered.proxy.CommonProxy",
				"com.magiology.forgepowered.proxy.ServerProxy",
				"com.magiology.handlers.animationhandlers.thehand.animation.AnimationEvent",
				"com.magiology.handlers.animationhandlers.thehand.animation.AnimationPart",
				"com.magiology.handlers.animationhandlers.thehand.animation.CommonHand",
				"com.magiology.handlers.animationhandlers.thehand.animation.HandAnimation",
				"com.magiology.handlers.animationhandlers.thehand.animation.HandAnimationBase",
				"com.magiology.handlers.animationhandlers.thehand.animation.LinearHandAnimation",
				"com.magiology.handlers.animationhandlers.thehand.animation.LinearHandAnimProgressHandler",
				"com.magiology.handlers.animationhandlers.thehand.HandData",
				"com.magiology.handlers.animationhandlers.thehand.HandPosition",
				"com.magiology.handlers.animationhandlers.thehand.TheHandHandler",
				"com.magiology.handlers.animationhandlers.WingsFromTheBlackFireHandler",
				"com.magiology.handlers.EnhancedRobot",
				"com.magiology.handlers.GuiHandlerM",
				"com.magiology.handlers.KeyHandler",
				"com.magiology.handlers.MyWorldData",
				"com.magiology.handlers.particle.IParticle",
				"com.magiology.handlers.particle.ParticleHandler",
				"com.magiology.handlers.particle.ParticleM",
				"com.magiology.handlers.particle.Particles",
				"com.magiology.handlers.PlayerClothPhysiscHandeler",
				"com.magiology.handlers.PremiumHandeler",
				"com.magiology.handlers.web.DownloadingHandler",
				"com.magiology.handlers.web.mediafire.core.ActionTreePart",
				"com.magiology.handlers.web.mediafire.core.MediaFireHandlerRunner",
				"com.magiology.handlers.web.mediafire.core.MFAction",
				"com.magiology.handlers.web.mediafire.packets.ActionPacket",
				"com.magiology.handlers.web.mediafire.packets.ListOfOutdatedFiles",
				"com.magiology.handlers.web.mediafire.packets.Ping",
				"com.magiology.handlers.web.mediafire.packets.WorkDone",
				"com.magiology.handlers.web.QuickMediaFireDownlader",
				"com.magiology.io.WorldData",
				"com.magiology.io.ZipManager",
				"com.magiology.mcobjects.blocks.fire.FireLamp",
				"com.magiology.mcobjects.blocks.fire.FirePipe",
				"com.magiology.mcobjects.blocks.HologramProjector",
				"com.magiology.mcobjects.blocks.JSProgrammer",
				"com.magiology.mcobjects.blocks.MultiColisionProviderBlock",
				"com.magiology.mcobjects.blocks.network.NetworkCommandHolder",
				"com.magiology.mcobjects.blocks.network.NetworkConductor",
				"com.magiology.mcobjects.blocks.network.NetworkController",
				"com.magiology.mcobjects.blocks.network.NetworkInterface",
				"com.magiology.mcobjects.blocks.network.NetworkRouter",
				"com.magiology.mcobjects.entitys.ComplexPlayerRenderingData",
				"com.magiology.mcobjects.entitys.EntityBallOfEnergy",
				"com.magiology.mcobjects.entitys.ExtendedPlayerData",
				"com.magiology.mcobjects.items.armor.Wings",
				"com.magiology.mcobjects.items.FireHammer",
				"com.magiology.mcobjects.items.IPowerSideInstructor",
				"com.magiology.mcobjects.items.ItemContainer",
				"com.magiology.mcobjects.items.NetworkPointer",
				"com.magiology.mcobjects.items.PowerCounter",
				"com.magiology.mcobjects.items.ProgramContainer",
				"com.magiology.mcobjects.items.TheHand",
				"com.magiology.mcobjects.particles.GuiParticle",
				"com.magiology.mcobjects.particles.ParticleFactory",
				"com.magiology.mcobjects.particles.ParticleMistBubble",
				"com.magiology.mcobjects.particles.ParticleMistBubbleFactory",
				"com.magiology.mcobjects.tileentityes.corecomponents.multibox.CollisionBox",
				"com.magiology.mcobjects.tileentityes.corecomponents.multibox.DefaultMultiColisionProvider",
				"com.magiology.mcobjects.tileentityes.corecomponents.multibox.MultiColisionProvider",
				"com.magiology.mcobjects.tileentityes.corecomponents.multibox.MultiColisionProviderHandler",
				"com.magiology.mcobjects.tileentityes.corecomponents.powertiles.TileEntityPow",
				"com.magiology.mcobjects.tileentityes.corecomponents.powertiles.TileEntityPowGen",
				"com.magiology.mcobjects.tileentityes.corecomponents.TileEntityConnectionProvider",
				"com.magiology.mcobjects.tileentityes.corecomponents.UpdateableTile",
				"com.magiology.mcobjects.tileentityes.hologram.Button",
				"com.magiology.mcobjects.tileentityes.hologram.Field",
				"com.magiology.mcobjects.tileentityes.hologram.HoloObject",
				"com.magiology.mcobjects.tileentityes.hologram.interactions.AbstractInteraction",
				"com.magiology.mcobjects.tileentityes.hologram.interactions.InteractionColor",
				"com.magiology.mcobjects.tileentityes.hologram.interactions.InteractionName",
				"com.magiology.mcobjects.tileentityes.hologram.interactions.InteractionPosition",
				"com.magiology.mcobjects.tileentityes.hologram.interactions.InteractionScale",
				"com.magiology.mcobjects.tileentityes.hologram.interactions.InteractionSize",
				"com.magiology.mcobjects.tileentityes.hologram.interactions.InteractionSlide",
				"com.magiology.mcobjects.tileentityes.hologram.interactions.InteractionText",
				"com.magiology.mcobjects.tileentityes.hologram.Point",
				"com.magiology.mcobjects.tileentityes.hologram.Slider",
				"com.magiology.mcobjects.tileentityes.hologram.StringContainer",
				"com.magiology.mcobjects.tileentityes.hologram.TextBox",
				"com.magiology.mcobjects.tileentityes.hologram.TileEntityHologramProjector",
				"com.magiology.mcobjects.tileentityes.network.interfaces.TileHologramProjectorInterface",
				"com.magiology.mcobjects.tileentityes.network.TileEntityNetworkConductor",
				"com.magiology.mcobjects.tileentityes.network.TileEntityNetworkController",
				"com.magiology.mcobjects.tileentityes.network.TileEntityNetworkInterface",
				"com.magiology.mcobjects.tileentityes.network.TileEntityNetworkProgramHolder",
				"com.magiology.mcobjects.tileentityes.network.TileEntityNetworkRouter",
				"com.magiology.mcobjects.tileentityes.TileEntityBateryGeneric",
				"com.magiology.mcobjects.tileentityes.TileEntityFireLamp",
				"com.magiology.mcobjects.tileentityes.TileEntityFirePipe",
				"com.magiology.registry.events.PlayerWrenchEvent",
				"com.magiology.registry.WrenchRegistry",
				"com.magiology.SoundM",
				"com.magiology.structures.BlockAt",
				"com.magiology.structures.Structure",
				"com.magiology.structures.Structures",
				"com.magiology.structures.SymmetryBoot",
				"com.magiology.util.renderers.FloatCalc",
				"com.magiology.util.renderers.GL11U",
				"com.magiology.util.renderers.glstates.GlState",
				"com.magiology.util.renderers.glstates.GlStateCell",
				"com.magiology.util.renderers.MultiTransfromModel",
				"com.magiology.util.renderers.OpenGLM",
				"com.magiology.util.renderers.Renderer",
				"com.magiology.util.renderers.ShinySurfaceRenderer",
				"com.magiology.util.renderers.tessellatorscripts.CubeModel",
				"com.magiology.util.renderers.tessellatorscripts.SidedModel",
				"com.magiology.util.renderers.tessellatorscripts.TexturedTriangle",
				"com.magiology.util.renderers.TessUtil",
				"com.magiology.util.renderers.ValueWithPrev",
				"com.magiology.util.renderers.VertexModel",
				"com.magiology.util.renderers.VertexRenderer",
				"com.magiology.util.utilclasses.CollectionConverter",
				"com.magiology.util.utilclasses.DataStalker",
				"com.magiology.util.utilclasses.FileUtil",
				"com.magiology.util.utilclasses.FontEffectUtil",
				"com.magiology.util.utilclasses.Get",
				"com.magiology.util.utilclasses.LogUtil",
				"com.magiology.util.utilclasses.math.ArrayMath",
				"com.magiology.util.utilclasses.math.MathUtil",
				"com.magiology.util.utilclasses.math.MatrixUtil",
				"com.magiology.util.utilclasses.math.PartialTicksUtil",
				"com.magiology.util.utilclasses.NetworkUtil",
				"com.magiology.util.utilclasses.PhysicsUtil",
				"com.magiology.util.utilclasses.PowerUtil",
				"com.magiology.util.utilclasses.PrintUtil",
				"com.magiology.util.utilclasses.RandUtil",
				"com.magiology.util.utilclasses.RayTracer",
				"com.magiology.util.utilclasses.SideUtil",
				"com.magiology.util.utilclasses.SpecialPlayerUtil",
				"com.magiology.util.utilclasses.UtilC",
				"com.magiology.util.utilclasses.UtilM",
				"com.magiology.util.utilobjects.ArrayListLog",
				"com.magiology.util.utilobjects.codeinsert.BooleanReturn",
				"com.magiology.util.utilobjects.codeinsert.ObjectConverter",
				"com.magiology.util.utilobjects.codeinsert.ObjectProcessor",
				"com.magiology.util.utilobjects.codeinsert.ObjectReturn",
				"com.magiology.util.utilobjects.ColorF",
				"com.magiology.util.utilobjects.ConvenientMap",
				"com.magiology.util.utilobjects.DoubleObject",
				"com.magiology.util.utilobjects.EntityPosAndBB",
				"com.magiology.util.utilobjects.IndexedModel",
				"com.magiology.util.utilobjects.LinearAnimation",
				"com.magiology.util.utilobjects.Matrix4fM",
				"com.magiology.util.utilobjects.MatrixStack",
				"com.magiology.util.utilobjects.m_extension.AxisAlignedBBM",
				"com.magiology.util.utilobjects.m_extension.BlockContainerM",
				"com.magiology.util.utilobjects.m_extension.BlockM",
				"com.magiology.util.utilobjects.m_extension.BlockPosM",
				"com.magiology.util.utilobjects.m_extension.effect.EntityCloudFXM",
				"com.magiology.util.utilobjects.m_extension.effect.EntityFlameFXM",
				"com.magiology.util.utilobjects.m_extension.effect.EntityLavaFXM",
				"com.magiology.util.utilobjects.m_extension.effect.EntitySmokeFXM",
				"com.magiology.util.utilobjects.m_extension.GuiContainerM",
				"com.magiology.util.utilobjects.m_extension.ItemM",
				"com.magiology.util.utilobjects.m_extension.SimpleNetworkWrapperM",
				"com.magiology.util.utilobjects.m_extension.TileEntityM",
				"com.magiology.util.utilobjects.m_extension.TileEntitySpecialRendererM",
				"com.magiology.util.utilobjects.NBTUtil",
				"com.magiology.util.utilobjects.ObjectHolder",
				"com.magiology.util.utilobjects.OhBabyATriple",
				"com.magiology.util.utilobjects.SimpleCounter",
				"com.magiology.util.utilobjects.SlowdownUtil",
				"com.magiology.util.utilobjects.Tracker",
				"com.magiology.util.utilobjects.ValueTracker",
				"com.magiology.util.utilobjects.vectors.AngularVec3",
				"com.magiology.util.utilobjects.vectors.physics.PhysicsFloat",
				"com.magiology.util.utilobjects.vectors.physics.PhysicsVec3F",
				"com.magiology.util.utilobjects.vectors.physics.real.AbstractRealPhysicsVec3F",
				"com.magiology.util.utilobjects.vectors.physics.real.entitymodel.Colideable",
				"com.magiology.util.utilobjects.vectors.physics.real.entitymodel.EntityModelColider",
				"com.magiology.util.utilobjects.vectors.physics.real.entitymodel.EntityPlayerModelColider",
				"com.magiology.util.utilobjects.vectors.physics.real.GeometryUtil",
				"com.magiology.util.utilobjects.vectors.physics.real.RealPhysicsMesh",
				"com.magiology.util.utilobjects.vectors.physics.real.RealPhysicsVec3F",
				"com.magiology.util.utilobjects.vectors.Plane",
				"com.magiology.util.utilobjects.vectors.Pos",
				"com.magiology.util.utilobjects.vectors.QuadUV",
				"com.magiology.util.utilobjects.vectors.QuadUVGenerator",
				"com.magiology.util.utilobjects.vectors.RayDeprecated",
				"com.magiology.util.utilobjects.vectors.TwoDots",
				"com.magiology.util.utilobjects.vectors.Vec2FM",
				"com.magiology.util.utilobjects.vectors.Vec2i",
				"com.magiology.util.utilobjects.vectors.Vec3M",
				"com.magiology.util.utilobjects.vectors.X1y1z1x2y2z2",
				"com.magiology.windowsgui.SoundPlayer"
			};
	
	protected static boolean error=false;
	
	static final Map<Class<?>, List<Class<?>>> implementations=new HashMap<>(),directImplementations=new HashMap<>();
	
	static final List<Class<?>> loadedClasses=new ArrayList<>();
	
	static List<Class<?>> getClassesToSort(){
		List<Class<?>> classes=new ArrayList<>();
		
		classes.add(IClassTransformer.class);
		classes.add(Calculable.class);
		classes.add(AbstractPacket.class);
		classes.add(TileEntityM.class);
		classes.add(ClassTransformerBase.class);
		
		return classes;
	}
	public static <T> List<Class<T>> getDirectImplementations(Class<T> clazz){
		List<Class<T>> list=new ArrayList<>();
		getDirectImplementations().get(clazz).forEach(c->list.add((Class<T>)c));
		return list;
	}
	public static Map<Class<?>, List<Class<?>>> getDirectImplementations(){
		ClassFinder.load();
		return directImplementations;
	}
	
	public static <T> List<Class<T>> getImplementations(Class<T> clazz){
		List<Class<T>> list=new ArrayList<>();
		getImplementations().get(clazz).forEach(c->list.add((Class<T>)c));
		return list;
	}
	public static Map<Class<?>, List<Class<?>>> getImplementations(){
		ClassFinder.load();
		return implementations;
	}
	
	public static List<Class<?>> getLoadedclasses(){
		ClassFinder.load();
		return loadedClasses;
	}
}
